apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.app.name }}-namespace
  labels:
    app: {{ .Values.app.name }}
data:
  APP_NAME: {{ .Values.config.appName }}
  APP_VERSION: {{ .Values.config.appVersion }}
  LOG_LEVEL: {{ .Values.config.logLevel }}
